version: '3'
services:

  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./db/tmp/redis:/data
    entrypoint: redis-server --appendonly yes

  postgres:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./db/tmp/db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
