version: '3'
services:

  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data/redis/data:/data
    entrypoint: redis-server --appendonly yes

  postgres:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./data/postgres/tmp:/var/lib/postgresql/data
      - ./data/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  fluentd:
    build: ./data/fluentd
    restart: always
    ports:
      - ${FLUENTD_PORT}:24224
      - ${FLUENTD_PORT}:24224/udp
    links:
      - postgres
    environment:
      - TRACK_DB_HOST=postgres
      - TRACK_DB_USER=${DB_USER}
      - TRACK_DB_PASS=${DB_PASS}
      - TRACK_DB_NAME=${DB_NAME}
    volumes:
      - ./data/fluentd/log:/fluentd/log
