CREATE ROLE deployer LOGIN PASSWORD 'pass';
CREATE DATABASE gin_test;
GRANT ALL PRIVILEGES ON DATABASE gin_test TO deployer;

CREATE TABLE IF NOT EXISTS todos (
  id SERIAL,
  title VARCHAR(255) NOT NULL ,
  complete BOOLEAN NOT NULL DEFAULT FALSE,
  created TIMESTAMP NOT NULL DEFAULT NOW()
);
